#!/usr/bin/env python3
"""Test the integrated snakenull plugin."""

import tempfile
import json
from pathlib import Path
from unittest.mock import patch, MagicMock


def test_integrated_snakenull():
    """Test snakenull plugin integration with real snakebids app."""

    # Mock config that would be generated by snakebids
    mock_config = {
        "pybids_inputs": {
            "dwi": {
                "filters": {"suffix": "dwi", "extension": [".nii.gz", ".nii"]},
                "zip_lists": {
                    "subject": ["01", "02", "01"],
                    "session": ["01", "01", "02"],
                    "run": ["1", "1", "1"],
                    "path": [
                        "/data/sub-01/ses-01/dwi/sub-01_ses-01_run-1_dwi.nii.gz",
                        "/data/sub-02/ses-01/dwi/sub-02_ses-01_run-1_dwi.nii.gz",
                        "/data/sub-01/ses-02/dwi/sub-01_ses-02_run-1_dwi.nii.gz",
                    ],
                },
            }
        }
    }

    # Test the plugin directly
    from snakebids.plugins import SnakenullPlugin

    plugin = SnakenullPlugin()

    print("Testing SnakenullPlugin.finalize_config()...")
    print("Original config:")
    print(json.dumps(mock_config["pybids_inputs"], indent=2))

    # Apply the plugin
    plugin.finalize_config(mock_config)

    print("\nAfter snakenull normalization:")
    print(json.dumps(mock_config["pybids_inputs"], indent=2))

    # Verify the results
    dwi_zip_lists = mock_config["pybids_inputs"]["dwi"]["zip_lists"]

    print("\nValidation:")
    print(f"- Total combinations: {len(dwi_zip_lists['subject'])}")

    # Should have 4 combinations (2 subjects × 2 sessions × 1 run)
    assert len(dwi_zip_lists["subject"]) == 4
    assert len(dwi_zip_lists["session"]) == 4
    assert len(dwi_zip_lists["run"]) == 4
    assert len(dwi_zip_lists["path"]) == 4

    # Count SNAKENULL entries
    null_count = sum(1 for path in dwi_zip_lists["path"] if path == "SNAKENULL")
    print(f"- SNAKENULL entries: {null_count}")
    assert null_count == 1  # sub-02/ses-02 should be missing

    # Verify all combinations exist
    combinations = set()
    for i in range(len(dwi_zip_lists["subject"])):
        combo = (
            dwi_zip_lists["subject"][i],
            dwi_zip_lists["session"][i],
            dwi_zip_lists["run"][i],
        )
        combinations.add(combo)

    expected_combinations = {
        ("01", "01", "1"),
        ("01", "02", "1"),
        ("02", "01", "1"),
        ("02", "02", "1"),
    }

    print(f"- Expected combinations: {sorted(expected_combinations)}")
    print(f"- Actual combinations: {sorted(combinations)}")
    assert combinations == expected_combinations

    print("\n✅ All tests passed! Plugin is working correctly.")

    return True


if __name__ == "__main__":
    test_integrated_snakenull()
