"""Snakenull Plugin for Snakebids.

This plugin applies snakenull normalization as a post-processing step after
input generation but before snakemake execution.
"""

from __future__ import annotations

import argparse
from typing import Any

import attrs

from snakebids import bidsapp
from snakebids.plugins.base import PluginBase


def apply_snakenull_to_inputs(inputs: dict[str, Any]) -> dict[str, Any]:
    """Apply snakenull normalization to snakebids inputs.

    This function takes the inputs dict generated by snakebids and applies
    snakenull normalization to handle heterogeneous BIDS datasets.

    Parameters
    ----------
    inputs : dict
        The inputs dictionary from snakebids config containing zip_lists

    Returns
    -------
    dict
        Normalized inputs with snakenull applied
    """
    # Deep copy to avoid modifying original
    import copy

    normalized_inputs = copy.deepcopy(inputs)

    for component_name, component_data in normalized_inputs.items():
        if not isinstance(component_data, dict) or "zip_lists" not in component_data:
            continue

        zip_lists = component_data["zip_lists"]
        if not zip_lists:
            continue

        # Apply snakenull normalization
        normalized_zip_lists = normalize_with_snakenull(zip_lists)
        component_data["zip_lists"] = normalized_zip_lists

        # Update other related fields
        if "path" in component_data:
            # Update the path list to match normalized zip_lists
            if normalized_zip_lists and "path" in normalized_zip_lists:
                component_data["path"] = normalized_zip_lists["path"]

    return normalized_inputs


def normalize_with_snakenull(zip_lists: dict[str, list]) -> dict[str, list]:
    """Normalize zip_lists using snakenull logic.

    This handles heterogeneous BIDS datasets by ensuring all entity combinations
    have consistent representations, adding null values where needed.

    Parameters
    ----------
    zip_lists : dict
        Dictionary where keys are entity names and values are lists of entity values

    Returns
    -------
    dict
        Normalized zip_lists with snakenull applied
    """
    if not zip_lists:
        return zip_lists

    # Get all entity keys except 'path' (which is special)
    entity_keys = [key for key in zip_lists.keys() if key != "path"]
    if not entity_keys:
        return zip_lists

    # Create normalized structure
    normalized = {key: [] for key in zip_lists.keys()}

    # Get unique combinations of all entities
    from itertools import product

    # First, find all unique values for each entity
    unique_values = {}
    for key in entity_keys:
        # Handle None values by converting to string representation
        values = zip_lists[key]
        clean_values = []
        for val in values:
            if val is None:
                clean_values.append("snakenull")  # Convert None to snakenull
            else:
                clean_values.append(str(val))
        unique_values[key] = sorted(set(clean_values))

    # Generate all possible combinations
    all_combinations = list(product(*[unique_values[key] for key in entity_keys]))

    # Create a mapping from combination to path (if it exists)
    existing_combinations = {}
    for i in range(len(zip_lists[entity_keys[0]])):
        # Convert None values to "snakenull" for consistency
        combo_values = []
        for key in entity_keys:
            val = zip_lists[key][i]
            if val is None:
                combo_values.append("snakenull")
            else:
                combo_values.append(str(val))
        combo = tuple(combo_values)
        if "path" in zip_lists and i < len(zip_lists["path"]):
            existing_combinations[combo] = zip_lists["path"][i]

    # Build normalized output
    for combo in all_combinations:
        # Add entity values
        for j, key in enumerate(entity_keys):
            normalized[key].append(combo[j])

        # Add path (existing or null)
        if "path" in zip_lists:
            if combo in existing_combinations:
                normalized["path"].append(existing_combinations[combo])
            else:
                # Use snakenull for missing combinations
                normalized["path"].append("SNAKENULL")

    return normalized


@attrs.define
class SnakenullPlugin(PluginBase):
    """Plugin that applies snakenull normalization to inputs.

    This plugin hooks into finalize_config to apply snakenull normalization
    after input generation but before snakemake execution.

    Parameters
    ----------
    enable : bool
        Whether to enable snakenull normalization (default: True)
    """

    enable: bool = attrs.field(default=True)

    @bidsapp.hookimpl
    def add_cli_arguments(
        self,
        parser: argparse.ArgumentParser,
        config: dict[str, Any],
        argument_groups: Any,
    ):
        """Add CLI arguments for snakenull configuration."""
        parser.add_argument(
            "--disable-snakenull",
            dest="plugins.snakenull.disable",
            action="store_true",
            help="Disable snakenull normalization of inputs",
        )
        parser.add_argument(
            "--enable-snakenull",
            dest="plugins.snakenull.enable",
            action="store_true",
            help="Enable snakenull normalization of inputs (default)",
        )

    @bidsapp.hookimpl
    def update_cli_namespace(self, namespace: dict[str, Any], config: dict[str, Any]):
        """Update enable flag based on CLI arguments."""
        if namespace.get("plugins.snakenull.disable", False):
            self.enable = False
        elif namespace.get("plugins.snakenull.enable", False):
            self.enable = True

        # Remove from namespace to avoid conflicts
        namespace.pop("plugins.snakenull.disable", None)
        namespace.pop("plugins.snakenull.enable", None)

    @bidsapp.hookimpl
    def finalize_config(self, config: dict[str, Any]):
        """Apply snakenull normalization to inputs after they're generated."""
        if not self.enable:
            return

        # Check if inputs exist in config
        if "pybids_inputs" not in config:
            return

        print("Applying snakenull normalization to inputs...")
        
        # Debug: Print original inputs
        print("DEBUG: Original pybids_inputs structure:")
        for component_name, component_data in config["pybids_inputs"].items():
            if isinstance(component_data, dict) and "zip_lists" in component_data:
                print(f"  Component: {component_name}")
                zip_lists = component_data["zip_lists"]
                for entity, values in zip_lists.items():
                    print(f"    {entity}: {values}")
                print()

        # Apply snakenull to inputs
        original_inputs = config["pybids_inputs"]
        normalized_inputs = apply_snakenull_to_inputs(original_inputs)

        # Update config with normalized inputs
        config["pybids_inputs"] = normalized_inputs

        # Debug: Print normalized inputs
        print("DEBUG: Normalized pybids_inputs structure:")
        for component_name, component_data in normalized_inputs.items():
            if isinstance(component_data, dict) and "zip_lists" in component_data:
                print(f"  Component: {component_name}")
                zip_lists = component_data["zip_lists"]
                for entity, values in zip_lists.items():
                    print(f"    {entity}: {values}")
                print()

        # Log the changes
        for component_name, component_data in normalized_inputs.items():
            if isinstance(component_data, dict) and "zip_lists" in component_data:
                zip_lists = component_data["zip_lists"]
                if zip_lists and "path" in zip_lists:
                    null_count = sum(
                        1 for path in zip_lists["path"] if path == "SNAKENULL"
                    )
                    total_count = len(zip_lists["path"])
                    if null_count > 0:
                        print(
                            f"  {component_name}: {total_count} total combinations "
                            f"({null_count} normalized with SNAKENULL)"
                        )
                    else:
                        print(
                            f"  {component_name}: {total_count} combinations (no normalization needed)"
                        )
