"""Snakenull Plugin for Snakebids.

This plugin applies snakenull normalization as a post-processing step after
input generation but before snakemake execution.
"""

from __future__ import annotations

import argparse
from typing import Any

import attrs

from snakebids import bidsapp
from snakebids.plugins.base import PluginBase


def apply_snakenull_to_inputs(inputs: dict[str, Any]) -> dict[str, Any]:
    """Apply snakenull normalization to snakebids inputs.

    This function takes the inputs dict generated by snakebids and applies
    snakenull normalization to handle heterogeneous BIDS datasets.

    Parameters
    ----------
    inputs : dict
        The inputs dictionary from snakebids config containing zip_lists

    Returns
    -------
    dict
        Normalized inputs with snakenull applied
    """
    # Deep copy to avoid modifying original
    import copy

    normalized_inputs = copy.deepcopy(inputs)

    for component_name, component_data in normalized_inputs.items():
        if not isinstance(component_data, dict) or "zip_lists" not in component_data:
            continue

        zip_lists = component_data["zip_lists"]
        if not zip_lists:
            continue

        # Apply snakenull normalization
        normalized_zip_lists = normalize_with_snakenull(zip_lists)
        component_data["zip_lists"] = normalized_zip_lists

        # Update other related fields
        if "path" in component_data:
            # Update the path list to match normalized zip_lists
            if normalized_zip_lists and "path" in normalized_zip_lists:
                component_data["path"] = normalized_zip_lists["path"]

    return normalized_inputs


def normalize_with_snakenull(zip_lists: dict[str, list]) -> dict[str, list]:
    """Normalize zip_lists using selective snakenull logic.

    This handles heterogeneous BIDS datasets by only normalizing missing entities
    within EXISTING file combinations, rather than creating false combinations.

    Parameters
    ----------
    zip_lists : dict
        Dictionary where keys are entity names and values are lists of entity values

    Returns
    -------
    dict
        Normalized zip_lists with snakenull applied to missing entities only
    """
    if not zip_lists:
        return zip_lists

    # Get all entity keys except 'path' (which is special)
    entity_keys = [key for key in zip_lists.keys() if key != "path"]
    if not entity_keys:
        return zip_lists

    # Create normalized structure - start with copy of original
    import copy
    normalized = copy.deepcopy(zip_lists)

    # Find all entities that exist across all files
    all_entities = set()
    for key in entity_keys:
        values = zip_lists[key]
        for val in values:
            if val is not None:
                all_entities.add(key)
                break

    # For each file combination, ensure all entities have values
    num_files = len(zip_lists[entity_keys[0]]) if entity_keys else 0
    
    for i in range(num_files):
        for key in entity_keys:
            if i < len(normalized[key]):
                val = normalized[key][i]
                # Convert None to "snakenull" for consistency
                if val is None:
                    normalized[key][i] = "snakenull"
                else:
                    normalized[key][i] = str(val)
            else:
                # Extend list if needed
                normalized[key].append("snakenull")

        # Ensure all entity lists have the same length
        for key in entity_keys:
            while len(normalized[key]) < num_files:
                normalized[key].append("snakenull")

    return normalized


@attrs.define
class SnakenullPlugin(PluginBase):
    """Plugin that applies snakenull normalization to inputs.

    This plugin hooks into finalize_config to apply snakenull normalization
    after input generation but before snakemake execution.

    Parameters
    ----------
    enable : bool
        Whether to enable snakenull normalization (default: True)
    """

    enable: bool = attrs.field(default=True)

    @bidsapp.hookimpl
    def add_cli_arguments(
        self,
        parser: argparse.ArgumentParser,
        config: dict[str, Any],
        argument_groups: Any,
    ):
        """Add CLI arguments for snakenull configuration."""
        parser.add_argument(
            "--disable-snakenull",
            dest="plugins.snakenull.disable",
            action="store_true",
            help="Disable snakenull normalization of inputs",
        )
        parser.add_argument(
            "--enable-snakenull",
            dest="plugins.snakenull.enable",
            action="store_true",
            help="Enable snakenull normalization of inputs (default)",
        )

    @bidsapp.hookimpl
    def update_cli_namespace(self, namespace: dict[str, Any], config: dict[str, Any]):
        """Update enable flag based on CLI arguments."""
        if namespace.get("plugins.snakenull.disable", False):
            self.enable = False
        elif namespace.get("plugins.snakenull.enable", False):
            self.enable = True

        # Remove from namespace to avoid conflicts
        namespace.pop("plugins.snakenull.disable", None)
        namespace.pop("plugins.snakenull.enable", None)

    @bidsapp.hookimpl
    def finalize_config(self, config: dict[str, Any]):
        """Apply snakenull normalization to inputs after they're generated."""
        if not self.enable:
            return

        print("Applying snakenull normalization to inputs...")

        # Debug: Print entire config structure to understand what's available
        print("DEBUG: Available config keys:", list(config.keys()))
        
        # Check multiple possible locations for inputs
        inputs_found = False
        input_locations = ["pybids_inputs", "inputs", "input_lists"]
        
        for location in input_locations:
            if location in config:
                print(f"DEBUG: Found inputs in config['{location}']")
                print(f"DEBUG: {location} structure:")
                for component_name, component_data in config[location].items():
                    print(f"  Component: {component_name}")
                    print(f"  Type: {type(component_data)}")
                    if isinstance(component_data, dict):
                        print(f"  Keys: {list(component_data.keys())}")
                        if "zip_lists" in component_data:
                            zip_lists = component_data["zip_lists"]
                            for entity, values in zip_lists.items():
                                print(f"    {entity}: {values}")
                        elif "path" in component_data:
                            print(f"    path: {component_data.get('path', 'N/A')}")
                    print()
                inputs_found = True
                break
        
        if not inputs_found:
            print("DEBUG: No inputs found in expected locations")
            print("DEBUG: Full config structure:")
            import pprint
            pprint.pprint(config)
            return

        # Check if inputs exist in config
        if "pybids_inputs" not in config:
            print("DEBUG: pybids_inputs not found, trying other locations...")
            # Try to find inputs in other locations
            for location in input_locations:
                if location in config:
                    print(f"DEBUG: Using inputs from {location}")
                    config["pybids_inputs"] = config[location]
                    break
            else:
                print("DEBUG: No suitable inputs found for normalization")
                return

        # Apply snakenull to inputs
        original_inputs = config["pybids_inputs"]
        normalized_inputs = apply_snakenull_to_inputs(original_inputs)

        # Update config with normalized inputs
        config["pybids_inputs"] = normalized_inputs

        # Debug: Print normalized inputs
        print("DEBUG: Normalized pybids_inputs structure:")
        for component_name, component_data in normalized_inputs.items():
            if isinstance(component_data, dict) and "zip_lists" in component_data:
                print(f"  Component: {component_name}")
                zip_lists = component_data["zip_lists"]
                for entity, values in zip_lists.items():
                    print(f"    {entity}: {values}")
                print()

        # Log the changes
        for component_name, component_data in normalized_inputs.items():
            if isinstance(component_data, dict) and "zip_lists" in component_data:
                zip_lists = component_data["zip_lists"]
                if zip_lists and "path" in zip_lists:
                    null_count = sum(
                        1 for path in zip_lists["path"] if path == "SNAKENULL"
                    )
                    total_count = len(zip_lists["path"])
                    if null_count > 0:
                        print(
                            f"  {component_name}: {total_count} total combinations "
                            f"({null_count} normalized with SNAKENULL)"
                        )
                    else:
                        print(
                            f"  {component_name}: {total_count} combinations (no normalization needed)"
                        )
